version: '3.5'
services:
  django:
    container_name: template-django-project
    image: localhost/template-django:latest
    networks:
      - django-network
    ports:
      - 8000:8000 
networks:
  django-network:
    name: compose-network